POST /api/2.3/transfers HTTP/1.0
Authorization: Basic YnJva2VyMzo=
Content-Length: 12
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "203e2ecb4aa245328f4a1027f636b894", 
    "token": "72056473dd7342f38716fbdadc758172"
  }, 
  "data": {
    "date": "2016-12-09T16:02:33.696057+02:00", 
    "id": "d57d310d2682fda164916e314f035fa3"
  }
}

